/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_detailed_metrics_RequestDataCollection */

#ifndef _Included_io_sqreen_detailed_metrics_RequestDataCollection
#define _Included_io_sqreen_detailed_metrics_RequestDataCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqreen_detailed_metrics_RequestDataCollection
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_sqreen_detailed_1metrics_RequestDataCollection_serialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
