/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_powerwaf_Powerwaf */

#ifndef _Included_io_sqreen_powerwaf_Powerwaf
#define _Included_io_sqreen_powerwaf_Powerwaf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    addRule
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_sqreen_powerwaf_Powerwaf_addRule
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    clearRule
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_Powerwaf_clearRule
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    runRule
 * Signature: (Ljava/lang/String;Ljava/util/Map;J)Lio/sqreen/powerwaf/Powerwaf/ActionWithData;
 */
JNIEXPORT jobject JNICALL Java_io_sqreen_powerwaf_Powerwaf_runRule
  (JNIEnv *, jclass, jstring, jobject, jlong);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_sqreen_powerwaf_Powerwaf_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
