/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_powerwaf_Powerwaf */

#ifndef _Included_io_sqreen_powerwaf_Powerwaf
#define _Included_io_sqreen_powerwaf_Powerwaf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    deinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_Powerwaf_deinitialize
  (JNIEnv *, jclass);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    addRule
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_sqreen_powerwaf_Powerwaf_addRule
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    clearRule
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_Powerwaf_clearRule
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    runRule
 * Signature: (Ljava/lang/String;Ljava/util/Map;Lio/sqreen/powerwaf/Powerwaf$Limits;)Lio/sqreen/powerwaf/Powerwaf/ActionWithData;
 */
JNIEXPORT jobject JNICALL Java_io_sqreen_powerwaf_Powerwaf_runRule__Ljava_lang_String_2Ljava_util_Map_2Lio_sqreen_powerwaf_Powerwaf_00024Limits_2
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    runRule
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;Lio/sqreen/powerwaf/Powerwaf$Limits;)Lio/sqreen/powerwaf/Powerwaf/ActionWithData;
 */
JNIEXPORT jobject JNICALL Java_io_sqreen_powerwaf_Powerwaf_runRule__Ljava_lang_String_2Ljava_nio_ByteBuffer_2Lio_sqreen_powerwaf_Powerwaf_00024Limits_2
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     io_sqreen_powerwaf_Powerwaf
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;Y
 */
JNIEXPORT jstring JNICALL Java_io_sqreen_powerwaf_Powerwaf_getVersion
  (JNIEnv *, jclass);

//////////////////////////////
///      Additive API
//////////////////////////////

/*
 * Class:     io.sqreen.powerwaf.Additive
 * Method:    initAdditive
 * Signature: (Ljava/lang/String;)Lio/sqreen/powerwaf/Additive;
 */
JNIEXPORT jobject JNICALL Java_io_sqreen_powerwaf_Additive_initAdditive
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io.sqreen.powerwaf.Additive
 * Method:    runAdditive
 * Signature: (Ljava/util/Map;Lio/sqreen/powerwaf/Powerwaf/Limits;)Lio/sqreen/powerwaf/Powerwaf/ActionWithData;
 */
JNIEXPORT jobject JNICALL Java_io_sqreen_powerwaf_Additive_runAdditive
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io.sqreen.powerwaf.Additive
 * Method:    clearAdditive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_Additive_clearAdditive
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
