#!/usr/bin/env bash
set -euo pipefail

readonly OUTPUT_NATIVE_LIBS_DIR="build/native_libs"

function cmd_build-docker-image() {
    echo "Building docker image..."
    docker build --platform "$OS/$ARCH" "$DOCKER_IMAGE" -t "libddwaf-build"
}

function cmd_build-libddwaf() {
    echo "Building libddwaf..."
    project_dir="$(pwd)/libddwaf"
    if [[ ! -d libddwaf ]]; then
        echo "libddwaf directory not found"
        exit 1
    fi
    mkdir -p libddwaf/Debug
    cd libddwaf/Debug

    cmake_args=()

    if [[ -n ${DEBUG:-} ]]; then
        cmake_args+=("-DCMAKE_BUILD_TYPE=Debug")
    else
        cmake_args+=("-DCMAKE_BUILD_TYPE=RelWithDebInfo")
    fi

    c_flags=
    if [[ $OS != windows ]]; then
        c_flags="$c_flags -fno-omit-frame-pointer"
    fi
    if [[ $OS = macos ]]; then
        c_flags="$c_flags -mmacosx-version-min=11.6"
    fi
    cmake_args+=("-DCMAKE_C_FLAGS=$c_flags")
    cmake_args+=("-DCMAKE_CXX_FLAGS=$c_flags")

    if [[ $OS = macos ]]; then
        cmake_args+=("-DLIBDDWAF_BUILD_STATIC=0")
    elif [[ $OS = windows ]]; then
        cmake_args+=("-DLIBDDWAF_BUILD_SHARED=0")
    fi

    if [[ $OS = macos && $ARCH = aarch64 ]]; then
        cmake_args+=("-DCMAKE_OSX_ARCHITECTURES=arm64")
    fi

    generator="Unix Makefiles"
    if [[ $OS = windows ]]; then
        generator="NMake Makefiles"
    fi

    cmake_args+=("-DCMAKE_INSTALL_PREFIX=$(pwd)/out/usr/local")

    cmake \
        "${cmake_args[@]}" \
        -G "$generator" \
        -S "$project_dir" \
        -B .

    cmake --build . --parallel "$(nproc)" --verbose

    cmake --build . --target install
}

function cmd_build-bindings-in-docker() {
    echo "Building JNI bindings in Docker..."
    docker run \
        --rm \
        --platform "$OS/$ARCH" \
        --user "$(id -u):$(id -g)" \
        -v "$(pwd):/work" \
        -w /work \
        "libddwaf-build" \
        ./ci/build build-bindings --os $OS --arch $ARCH --libc $LIBC
}

function cmd_build-bindings() {
    echo "Building JNI bindings..."
    project_dir="$(pwd)"
    mkdir -p "$OUTPUT_NATIVE_LIBS_DIR"
    mkdir -p /tmp/build
    cd /tmp/build

    cmake_args=("-DCMAKE_BUILD_TYPE=RelWithDebInfo")

    c_flags=
    if [[ $OS != windows ]]; then
        c_flags="$c_flags -fno-omit-frame-pointer"
    fi
    if [[ $OS = macos ]]; then
        c_flags="$c_flags -mmacosx-version-min=11.6"
    fi
    cmake_args+=("-DCMAKE_C_FLAGS=$c_flags")
    cmake_args+=("-DCMAKE_CXX_FLAGS=$c_flags")

    if [[ $OS = macos && $ARCH = aarch64 ]]; then
        cmake_args+=("-DCMAKE_OSX_ARCHITECTURES=arm64")
    fi

    cmake_args+=("-DCMAKE_PREFIX_PATH=$project_dir/libddwaf/Debug/out/usr/local")

    generator="Unix Makefiles"
    if [[ $OS = windows ]]; then
        generator="NMake Makefiles"
    fi

    cmake \
        "${cmake_args[@]}" \
        -G "$generator" \
        -S "$project_dir" \
        -B .

    cmake --build . --parallel "$(nproc)" --verbose

    if [[ $OS = linux ]]; then
        output_path="$project_dir/$OUTPUT_NATIVE_LIBS_DIR/$OS/$ARCH/$LIBC"
        mkdir -p "$output_path"
        cp libsqreen_jni.so "$output_path/"
        cp libsqreen_jni.so.debug "$output_path/"
        cp "$project_dir/libddwaf/Debug/out/usr/local/lib/libddwaf.so" "$project_dir/$OUTPUT_NATIVE_LIBS_DIR/$OS/$ARCH/"
    elif [[ $OS = macos ]]; then
        output_path="$project_dir/$OUTPUT_NATIVE_LIBS_DIR/$OS/$ARCH"
        mkdir -p "$output_path"
        cp libsqreen_jni.dylib "$output_path/"
        cp libsqreen_jni.dylib.dwarf "$output_path/"
        cp "$project_dir/libddwaf/Debug/out/usr/local/lib/libddwaf.dylib" "$output_path/"
        cp "$project_dir/libddwaf/Debug/libddwaf.dylib.dwarf" "$output_path/"
    elif [[ $OS = windows ]]; then
        output_path="$project_dir/$OUTPUT_NATIVE_LIBS_DIR/$OS/$ARCH"
        mkdir -p "$output_path"
        cp sqreen_jni.dll "$output_path/"
        cp sqreen_jni.pdb "$output_path/"
    else
        echo "Invalid OS: $OS"
        exit 1
    fi
}

function cmd_run-tests-in-docker() {
    echo "Run tests in Docker..."
    docker run \
        --rm \
        --platform "$OS/$ARCH" \
        --user "$(id -u):$(id -g)" \
        -v "$(pwd):/work" \
        -w /work \
        "libddwaf-build" \
        ./ci/build run-tests
}

function cmd_run-tests() {
    echo "Run tests..."
    ./gradlew check --info -Prelease
}

function get_libddwaf_version() {
    grep -E 'set\(LIBDDWAF_VERSION\s+[0-9.a-zA-Z]+\)' deps/CMakeLists.txt | sed -e 's~.*\s\(.*\)).*~\1~g'
}

function cmd_get-libddwaf-version() {
    get_libddwaf_version
}

COMMAND="$1"
shift

# Parse options
DEBUG=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --arch)
            ARCH="$2"
            shift 2
            ;;
        --os)
            OS="$2"
            shift 2
            ;;
        --libc)
            LIBC="$2"
            shift 2
            ;;
        --debug)
            DEBUG=true
            shift
            ;;
        --docker-image)
            DOCKER_IMAGE="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ -z ${DOCKER_IMAGE:-} ]]; then
    case "${OS:-}-${ARCH:-}-${LIBC:-}" in
        linux-*-glibc)
            DOCKER_IMAGE="ci/manylinux/$ARCH"
            ;;
        linux-*-musl)
            DOCKER_IMAGE="ci/alpine"
            ;;
        *)
            DOCKER_IMAGE=
            ;;
    esac
fi

# check if function cmd_$COMMAND exists, and then run it:
if declare -F "cmd_$COMMAND" &> /dev/null; then
    "cmd_$COMMAND" "$@"
else
    echo "Bad command: $COMMAND"
    exit 1
fi
