/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_WafBuilder */

#ifndef _Included_com_datadog_ddwaf_WafBuilder
#define _Included_com_datadog_ddwaf_WafBuilder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    addOrUpdateConfig
 * Signature: (Lcom/datadog/ddwaf/WafBuilder;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_datadog_ddwaf_WafBuilder_addOrUpdateRuleConfig(JNIEnv *, jclass, jobject,
                                                            jstring, jobject, jobject);

JNIEXPORT void JNICALL Java_com_datadog_ddwaf_WafBuilder_removeRuleConfig(JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    initBuilder
 */
JNIEXPORT jlong JNICALL Java_com_datadog_ddwaf_WafBuilder_initBuilder(JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    build
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_WafBuilder_build(JNIEnv *, jclass, jlong);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    buildInstance
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_WafBuilder_buildInstance(JNIEnv *, jclass, jobject, jobject);

JNIEXPORT void JNICALL Java_com_datadog_ddwaf_WafBuilder_destroyBuilder(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
