/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_CharSequenceWrapper */

#ifndef _Included_com_datadog_ddwaf_CharSequenceWrapper
#define _Included_com_datadog_ddwaf_CharSequenceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datadog_ddwaf_CharSequenceWrapper
 * Method:    resetState
 * Signature: (Ljava/nio/CharBuffer;Ljava/lang/CharSequence;)V
 */
JNIEXPORT void JNICALL Java_com_datadog_ddwaf_CharSequenceWrapper_resetState(
        JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
