/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_WafContext */

#ifndef _Included_com_datadog_ddwaf_WafContext
#define _Included_com_datadog_ddwaf_WafContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datadog_ddwaf_WafContext
 * Method:    initWafContext
 * Signature: (Lcom/datadog/ddwaf/NativeWafHandle;)J
 */
JNIEXPORT jlong JNICALL
Java_com_datadog_ddwaf_WafContext_initWafContext(JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_WafContext
 * Method:    runWafContext
 * Signature:
 * (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Lcom/datadog/ddwaf/Waf$Limits;Lcom/datadog/ddwaf/WafMetrics;)Lcom/datadog/ddwaf/Waf$ResultWithData;
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_WafContext_runWafContext(
        JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_datadog_ddwaf_WafContext
 * Method:    clearWafContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_datadog_ddwaf_WafContext_clearWafContext(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
