/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_ByteBufferSerializer */

#ifndef _Included_com_datadog_ddwaf_ByteBufferSerializer
#define _Included_com_datadog_ddwaf_ByteBufferSerializer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_datadog_ddwaf_ByteBufferSerializer_NULLPTR
#define com_datadog_ddwaf_ByteBufferSerializer_NULLPTR 0LL
#undef com_datadog_ddwaf_ByteBufferSerializer_SIZEOF_PWARGS
#define com_datadog_ddwaf_ByteBufferSerializer_SIZEOF_PWARGS 40L
#undef com_datadog_ddwaf_ByteBufferSerializer_PWARGS_MIN_SEGMENTS_SIZE
#define com_datadog_ddwaf_ByteBufferSerializer_PWARGS_MIN_SEGMENTS_SIZE 512L
#undef com_datadog_ddwaf_ByteBufferSerializer_STRINGS_MIN_SEGMENTS_SIZE
#define com_datadog_ddwaf_ByteBufferSerializer_STRINGS_MIN_SEGMENTS_SIZE 81920L
/*
 * Class:     com_datadog_ddwaf_ByteBufferSerializer
 * Method:    getByteBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL
Java_com_datadog_ddwaf_ByteBufferSerializer_getByteBufferAddress(JNIEnv *,
                                                                 jclass,
                                                                 jobject);

#ifdef __cplusplus
}
#endif
#endif
