/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_Waf */

#ifndef _Included_com_datadog_ddwaf_Waf
#define _Included_com_datadog_ddwaf_Waf
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_datadog_ddwaf_NativeWafHandle_destroyNativeWafHandle(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
