/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_Waf */

#ifndef _Included_com_datadog_ddwaf_Waf
#define _Included_com_datadog_ddwaf_Waf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    pwArgsBufferToString
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_datadog_ddwaf_Waf_pwArgsBufferToString(JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datadog_ddwaf_Waf_getVersion(JNIEnv *,
                                                                jclass);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    deinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_datadog_ddwaf_Waf_deinitialize(JNIEnv *,
                                                               jclass);

#ifdef __cplusplus
}
#endif
#endif
