/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_powerwaf_ByteBufferSerializer */

#ifndef _Included_io_sqreen_powerwaf_ByteBufferSerializer
#define _Included_io_sqreen_powerwaf_ByteBufferSerializer
#ifdef __cplusplus
extern "C" {
#endif
#undef io_sqreen_powerwaf_ByteBufferSerializer_NULLPTR
#define io_sqreen_powerwaf_ByteBufferSerializer_NULLPTR 0LL
#undef io_sqreen_powerwaf_ByteBufferSerializer_SIZEOF_PWARGS
#define io_sqreen_powerwaf_ByteBufferSerializer_SIZEOF_PWARGS 40L
#undef io_sqreen_powerwaf_ByteBufferSerializer_PWARGS_MIN_SEGMENTS_SIZE
#define io_sqreen_powerwaf_ByteBufferSerializer_PWARGS_MIN_SEGMENTS_SIZE 512L
#undef io_sqreen_powerwaf_ByteBufferSerializer_STRINGS_MIN_SEGMENTS_SIZE
#define io_sqreen_powerwaf_ByteBufferSerializer_STRINGS_MIN_SEGMENTS_SIZE 81920L
/*
 * Class:     io_sqreen_powerwaf_ByteBufferSerializer
 * Method:    getByteBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_sqreen_powerwaf_ByteBufferSerializer_getByteBufferAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
