/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_powerwaf_CharSequenceWrapper */

#ifndef _Included_io_sqreen_powerwaf_CharSequenceWrapper
#define _Included_io_sqreen_powerwaf_CharSequenceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqreen_powerwaf_CharSequenceWrapper
 * Method:    resetState
 * Signature: (Ljava/nio/CharBuffer;Ljava/lang/CharSequence;)V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_CharSequenceWrapper_resetState
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
