/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqreen_powerwaf_PowerwafMetrics */

#ifndef _Included_io_sqreen_powerwaf_PowerwafMetrics
#define _Included_io_sqreen_powerwaf_PowerwafMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqreen_powerwaf_PowerwafMetrics
 * Method:    init
 * Signature: (Lio/sqreen/powerwaf/PowerwafMetrics;)V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_PowerwafMetrics_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_sqreen_powerwaf_PowerwafMetrics
 * Method:    copyResults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_PowerwafMetrics_copyResults
  (JNIEnv *, jobject);

/*
 * Class:     io_sqreen_powerwaf_PowerwafMetrics
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_sqreen_powerwaf_PowerwafMetrics_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
