/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_ddwaf_Waf */

#ifndef _Included_com_datadog_ddwaf_Waf
#define _Included_com_datadog_ddwaf_Waf
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    clearRules
 * Signature: (Lcom/datadog/ddwaf/WafHandle;)V
 */
JNIEXPORT void JNICALL Java_com_datadog_ddwaf_Waf_clearRules
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    getKnownAddresses
 * Signature: (Lcom/datadog/ddwaf/WafHandle;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datadog_ddwaf_Waf_getKnownAddresses
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    getKnownActions
 * Signature: (Lcom/datadog/ddwaf/WafHandle;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datadog_ddwaf_Waf_getKnownActions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    runRules
 * Signature: (Lcom/datadog/ddwaf/WafHandle;Ljava/nio/ByteBuffer;Lcom/datadog/ddwaf/Waf$Limits;Lcom/datadog/ddwaf/WafMetrics;)Lcom/datadog/ddwaf/Waf$ResultWithData;
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_Waf_runRules
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    pwArgsBufferToString
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datadog_ddwaf_Waf_pwArgsBufferToString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datadog_ddwaf_Waf_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    deinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_datadog_ddwaf_Waf_deinitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    addOrUpdateConfig
 * Signature: (Lcom/datadog/ddwaf/WafBuilder;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_datadog_ddwaf_WafBuilder_addOrUpdateRuleConfig(JNIEnv *, jclass, jobject,
                                                            jstring, jstring, jobject, jobject);

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    initBuilder
 */
JNIEXPORT jlong JNICALL Java_com_datadog_ddwaf_WafBuilder_initBuilder(JNIEnv *, jclass, jobject);

/*
 * Class:     com_datadog_ddwaf_Builder
 * Method:    build
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_Builder_build(JNIEnv *, jclass, jlong);

/*
 * Class:     com_datadog_ddwaf_Waf
 * Method:    buildInstance
 */
JNIEXPORT jobject JNICALL Java_com_datadog_ddwaf_Waf_buildInstance(JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
